config/routes.rb
Hackerboard::Application.routes.draw do
  # scope "/:locale" do
    root :to => "questions#index"

    namespace :admin do
      resources :categories do
        member do
          get :remove
        end
      end
    end

    controller :feed do
      get "/feed/questions/:id", :action => :replies, :as => :replies_feed
      get "/feed/questions", :action => :questions, :as => :questions_feed
      get "/feed/categories/:id", :action => :categories, :as => :category_feed
    end

    controller :users do
      get "/signup", :action => :new
      post "/signup", :action => :create, :as => false
      get "/users/:id", :action => :show, :as => :user
    end

    controller :categories do
      get "/category/:id", :action => :show, :as => :category
    end

    controller :questions do
      get "/questions", :action => :index, :as => :questions
      get "/questions/new", :action => :new, :as => :new_question
      post "/questions/new", :action => :create, :as => false
      get "/questions/search", :action => :search, :as => :search_questions
      get "/questions/:id", :action => :show, :as => :question
    end

    controller :replies do
      post "/questions/:question_id/replies/new", :action => :create, :as => :new_reply
    end

    controller :sessions do
      get "/login", :action => :new
      post "/login", :action => :create, :as => false
      get "/logout", :action => :destroy
    end
  # end
end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_readonly :user_id
  attr_accessible :title, :body, :category_id

  belongs_to :user, :counter_cache => true
  belongs_to :category, :counter_cache => true
  has_many :replies, :dependent => :destroy

  scope :recent, order("id desc")
  scope :unanswered, where(:replies_count => 0)
  scope :to_feed, includes(:user).limit(10).order("id desc")

  validates_presence_of :title, :body, :category, :user

  define_index do
    set_property :delta => true

    indexes title
    indexes body
  end

  def viewed!
    increment!(:views_count)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  require_logged_user :only => [:new, :create]

  helper_method :categories

  rescue_from Riddle::ConnectionError do
    redirect_to root_path, :alert => t("flash.questions.search.alert")
  end

  rescue_from ActiveRecord::RecordNotFound do
    case request.format.symbol
    when :html
      render :file => Rails.root.join("public/404.html"), :layout => false, :status => 404
    when :json
      render :json => {:error => "Question not found"}, :status => 404
    end
  end

  def index
    @questions = QuestionFilter.filter(params)
    @sidebar = QuestionsSidebarPresenter.new

    respond_to do |format|
      format.html
      format.json { render :json => @questions }
    end
  end

  def search
    @questions = QuestionSearch.search(params)
  end

  def show
    @question = Question.find(params[:id])
    @question.viewed!

    @reply = Reply.new
    @reply_form = ReplyFormPresenter.new(current_user, @question, @reply)
  end

  def new
    @question = Question.new

    render :layout => "window"
  end

  def create
    @question = current_user.questions.new(params[:question])

    if @question.save
      redirect_to question_path(@question), :notice => t("flash.questions.create.notice")
    else
      render :new, :layout => "window"
    end
  end

  private
  def categories
    @categories ||= Category.scoped
  end
end

app/views/questions/_categories.html.erb
<h1><%= t("sidebar.categories") %></h1>

<ul class="categories">
  <% categories.each do |category| %>
    <li>
      <%= link_to category.name, category_path(category) %>
      <%= t("category.questions_html", :count => category.questions_count) %>
    </li>
  <% end %>
</ul>

app/views/questions/_question.html.erb
<article class="post">
  <h2><%= link_to question.title, question_path(question) %></h2>
  <ul class="meta">
    <li>
      <%= profile_link(question.user) %>
    </li>

    <li class="published-at">
      <%= t("question.published_at", :time => time_ago_in_words(question.created_at)) %>
    </li>

    <li class="icon view">
      <%= t("question.views_html", :count => question.views_count) %>
    </li>

    <li class="icon reply">
      <%= t("question.replies_html", :count => question.replies_count) %>
    </li>
  </ul>
</article>

app/views/questions/_search.html.erb
<h1><%= t("sidebar.search") %></h1>

<%= form_tag search_questions_path, :method => :get, :class => "search" do %>
  <p>
    <%= search_field_tag :query %>
    <%= submit_tag t("form.buttons.search") %>
  </p>
<% end %>

app/views/questions/_users.html.erb
<h1><%= t("sidebar.users") %></h1>

<ul class="users">
  <% users.each do |user| %>
    <li>
      <%= profile_link user %>
    </li>
  <% end %>
</ul>

app/views/questions/index.html.erb
<h1>Últimas perguntas</h1>

<dl class="filters">
  <dt>Filter posts</dt>

  <dd><%= link_to t("filter.all"), questions_path %></dd>
  <dd><%= link_to t("filter.unanswered"), questions_path(:filter => QuestionFilter::UNANSWERED) %></dd>
</dl>

<% content_for :paginate do %>
  <%= paginate @questions %>
<% end %>

<% iterate @questions do |question| %>
  <%= render question %>
<% end %>

<%= yield :paginate %>

<% content_for :sidebar do %>
  <%= render "categories", :categories => @sidebar.categories %>
  <%= render "users", :users => @sidebar.users %>
<% end %>

app/views/questions/new.html.erb
<%= form_for @question, :url => new_question_path do |f| %>
  <%= render "shared/error_messages", :record => @question %>

  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= error_for @question, :title %>
  </p>

  <p>
    <%= f.label :body %>
    <%= f.text_area :body %>
    <%= error_for @question, :body %>
  </p>

  <p>
    <%= f.label :category_id %>
    <%= f.collection_select :category_id, categories, :id, :name, :include_blank => true %>
    <%= error_for @question, :category %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/questions/search.html.erb
<h1>Sua busca</h1>
<p>
  Sua busca por <strong><%= params[:query].inspect %></strong>
  retornou os seguintes resultados:
</p>

<% iterate @questions do |question| %>
  <%= render question %>
<% end %>

<%= paginate @questions %>

app/views/questions/show.html.erb
<article>
  <h1><%= @question.title %></h1>

  <%= simple_format @question.body %>

  <p class="about">
    <%= profile_link(@question.user) %>
    <%= t("question.about_question", :time => l(@question.created_at, :format => :short)) %>
  </p>
</article>

<h2><%= t("question.replies_html", :count => @question.replies_count) %></h2>

<%= render @question.replies %>
<%= render @reply_form.partial %>

<% content_for :sidebar do %>
  <h3><%= t("sidebar.about") %></h3>

  <ul class="stats">
    <li>
      <%= t("question.views_html", :count => @question.views_count) %>
    </li>

    <li>
      <%= t("question.replies_html", :count => @question.replies_count) %>
    </li>

    <li>
      <%= link_to "RSS", replies_feed_path(@question), :class => "feed" %>
    </li>
  </ul>
<% end %>