config/routes.rb
Hackerboard::Application.routes.draw do
  # scope "/:locale" do
    root :to => "questions#index"

    namespace :admin do
      resources :categories do
        member do
          get :remove
        end
      end
    end

    controller :feed do
      get "/feed/questions/:id", :action => :replies, :as => :replies_feed
      get "/feed/questions", :action => :questions, :as => :questions_feed
      get "/feed/categories/:id", :action => :categories, :as => :category_feed
    end

    controller :users do
      get "/signup", :action => :new
      post "/signup", :action => :create, :as => false
      get "/users/:id", :action => :show, :as => :user
    end

    controller :categories do
      get "/category/:id", :action => :show, :as => :category
    end

    controller :questions do
      get "/questions", :action => :index, :as => :questions
      get "/questions/new", :action => :new, :as => :new_question
      post "/questions/new", :action => :create, :as => false
      get "/questions/search", :action => :search, :as => :search_questions
      get "/questions/:id", :action => :show, :as => :question
    end

    controller :replies do
      post "/questions/:question_id/replies/new", :action => :create, :as => :new_reply
    end

    controller :sessions do
      get "/login", :action => :new
      post "/login", :action => :create, :as => false
      get "/logout", :action => :destroy
    end
  # end
end

app/views/shared/_error_messages.html.erb
<% unless record.errors.empty? %>
  <dl class="error-messages">
    <dt><%= t("form.error_messages") %></dt>

    <% record.errors.full_messages.each do |message| %>
      <dd><%= message %></dd>
    <% end %>
  </dl>
<% end %>

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <p class="<%= type %> message"><%= message %></p>
<% end %>

app/views/shared/_header.html.erb
<header class="main container">
  <%= link_to image_tag("hackerboard.png"), root_path %>

  <% if logged_in? %>
    <p>
      <%= t("user.greeting", :name => current_user.name) %>
    </p>
  <% end %>

  <nav>
    <ul>
      <li class="new-question"><%= link_to t("nav.new_question"), new_question_path %></li>

      <% if logged_in? %>
        <li class="logout"><%= link_to t("nav.logout"), logout_path, :class => "button" %></li>
      <% else %>
        <li class="signup"><%= link_to t("nav.signup"), signup_path %></li>
        <li class="login"><%= link_to t("nav.login"), login_path %></li>
      <% end %>
    </ul>
  </nav>
</header>