config/routes.rb
Hackerboard::Application.routes.draw do
  # scope "/:locale" do
    root :to => "questions#index"

    namespace :admin do
      resources :categories do
        member do
          get :remove
        end
      end
    end

    controller :feed do
      get "/feed/questions/:id", :action => :replies, :as => :replies_feed
      get "/feed/questions", :action => :questions, :as => :questions_feed
      get "/feed/categories/:id", :action => :categories, :as => :category_feed
    end

    controller :users do
      get "/signup", :action => :new
      post "/signup", :action => :create, :as => false
      get "/users/:id", :action => :show, :as => :user
    end

    controller :categories do
      get "/category/:id", :action => :show, :as => :category
    end

    controller :questions do
      get "/questions", :action => :index, :as => :questions
      get "/questions/new", :action => :new, :as => :new_question
      post "/questions/new", :action => :create, :as => false
      get "/questions/search", :action => :search, :as => :search_questions
      get "/questions/:id", :action => :show, :as => :question
    end

    controller :replies do
      post "/questions/:question_id/replies/new", :action => :create, :as => :new_reply
    end

    controller :sessions do
      get "/login", :action => :new
      post "/login", :action => :create, :as => false
      get "/logout", :action => :destroy
    end
  # end
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name

  has_many :questions, :dependent => :destroy

  validates_presence_of :name

  scope :sorted_by_name, order("name asc")

  default_scope where(:deleted_at => nil)

  def self.to_be_removed
    unscoped.where("deleted_at is not null")
  end

  def remove!
    update_attribute :deleted_at, Time.now
  end
end

app/controllers/admin/categories_controller.rb
module Admin
  class CategoriesController < AdminController
    def index
      @categories = Category.sorted_by_name
    end

    def remove
      @category = Category.find(params[:id])
    end

    def destroy
      @category = Category.find(params[:id])
      @category.remove!
      redirect_to admin_categories_path, :notice => t("flash.admin.categories.destroy.notice")
    end

    def new
      @category = Category.new
    end

    def create
      @category = Category.new(params[:category])

      if @category.save
        redirect_to admin_categories_path, :notice => t("flash.admin.categories.create.notice")
      else
        render :new
      end
    end

    def edit
      @category = Category.find(params[:id])
    end

    def update
      @category = Category.find(params[:id])

      if @category.update_attributes(params[:category])
        redirect_to admin_categories_path, :notice => t("flash.admin.categories.update.notice")
      else
        render :edit
      end
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    render :text => "WIP"
  end
end

app/views/admin/categories/_form.html.erb
<%= form_for [:admin, category] do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/admin/categories/edit.html.erb
<%= render "form", :category => @category %>

app/views/admin/categories/index.html.erb
<% @categories.each do |category| %>
  <p>
    <%= link_to category.name, edit_admin_category_path(category) %>
    <%= link_to "Remove", remove_admin_category_path(category) %>
    <%= link_to "Edit", edit_admin_category_path(category) %>
  </p>
<% end %>

<p>
  <%= link_to "Add category", new_admin_category_path %>
</p>

app/views/admin/categories/new.html.erb
<%= render "form", :category => @category %>

app/views/admin/categories/remove.html.erb
<p>
  Você quer mesmo remover <strong><%= @category.name %></strong>?
  <br>
  Não será possível desfazer esta ação.
</p>

<%= button_to "Sim, tenho certeza!", admin_category_path(@category), :method => :delete %>